"""delete row

Revision ID: f3476d5b95a8
Revises: 8e72b7e50c5b
Create Date: 2020-02-23 22:49:07.552216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3476d5b95a8'
down_revision = '8e72b7e50c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'deleted')
    # ### end Alembic commands ###
